Epoch: [1/100], Step: [50/261], Loss: 2.349405288696289
Epoch: [1/100], Step: [100/261], Loss: 2.2720847129821777
Epoch: [1/100], Step: [150/261], Loss: 1.9408893585205078
Epoch: [1/100], Step: [200/261], Loss: 1.5643467903137207
Epoch: [1/100], Step: [250/261], Loss: 1.624880075454712
text loss: tensor(1.4662)
RMSE: nan deg/s
median of relative error: nan
/home/ljw/anaconda3/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3372: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ljw/anaconda3/lib/python3.8/site-packages/numpy/core/_methods.py:170: RuntimeWarning: invalid value encountered in true_divide
  ret = ret.dtype.type(ret / rcount)
Epoch: [2/100], Step: [50/261], Loss: 1.4061119556427002
Epoch: [2/100], Step: [100/261], Loss: 1.263758659362793
Epoch: [2/100], Step: [150/261], Loss: 1.1107412576675415
Epoch: [2/100], Step: [200/261], Loss: 1.1705431938171387
Epoch: [2/100], Step: [250/261], Loss: 0.9989150166511536
text loss: tensor(1.0323)
Traceback (most recent call last):
  File "train.py", line 33, in <module>
    trainer.train(num_epochs=100, learning_rate=0.0001)  # LR 不能设置更大 否则无法收敛
  File "/home/ljw/Projects/6Dof_tracking/utils/testing_6Dof.py", line 107, in train
    self.test()
  File "/home/ljw/Projects/6Dof_tracking/utils/testing_6Dof.py", line 136, in test
    self.data_collector.writeToDisk(self.output_dir)
  File "/home/ljw/Projects/6Dof_tracking/utils/testing_6Dof.py", line 160, in writeToDisk
    np.save(os.path.join(out_dir, 'predictions.npy'), pred)
  File "<__array_function__ internals>", line 5, in save
  File "/home/ljw/anaconda3/lib/python3.8/site-packages/numpy/lib/npyio.py", line 524, in save
    file_ctx = open(file, "wb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/ljw/Projects/6Dof_tracking/logs/train/20210712-161452/out/predictions.npy'
